### ISSUE TITLE
can not run the stable cascade workflow successfully

### ISSUE THREAD

**Issue by zcfrank1st** [XmYx/deforum-comfy-nodes#10]
do not change any config, just modify the prompt, got the error below
![1708518659981](https://github.com/XmYx/deforum-comfy-nodes/assets/1767976/b25fd36c-f2e7-4001-afdf-44358dd7fb69)

**Comment by XmYx** [comment]
I'll check in the evening, but until then can you right click the iterator node, and select Fix node, then make sure the output latent is still connected, furthermore, that "stable_cascade" is selected as latent_type. Thank you

**Comment by zcfrank1st** [comment]
ok , I'll try it. Thank you

**Comment by zcfrank1st** [comment]
I have checked the iterator node and latent_type, both ok

**Comment by XmYx** [comment]
new stable cascade workflow has been added that's compatible with the comfy style models.
https://comfyanonymous.github.io/ComfyUI_examples/stable_cascade/
