### ISSUE TITLE
fail to load deforum nodes

### ISSUE THREAD

**Issue by renatodigiorgio** [XmYx/deforum-comfy-nodes#11]
Install through the link - https://www.github.com/XmYx/deforum-comfy-nodes - using git clone (run at my ...ComfyUI\custom_nodes ) and try to open the simpler workflow with examples (deforum_simple.json) and obtain this error. I see the files, but may be i install wrong. Anyone help me with this issue?

![Screenshot_1](https://github.com/XmYx/deforum-comfy-nodes/assets/28816491/6962bd9e-ced3-47df-af4c-dcb53d67aa73)

**Comment by XmYx** [comment]
Hi!

Can you try reinstalling the nodes (delete deforum-comfy-nodes, run comfy, git clone to custom nodes, run comfy) and paste the command prompt output?

**Comment by renatodigiorgio** [comment]
ok @XmYx ! thanks for the tip. i delete now and restart... install it again using the comfyui manager >> install via git url and works like a charm! many thanks! can't wait for test deforum on comfyui! ❤😍 thanks again @XmYx 🙏

![Screenshot_2](https://github.com/XmYx/deforum-comfy-nodes/assets/28816491/2d939e08-c295-4e6f-9260-ddd7ef8b35c1)
