### ISSUE TITLE
Trouble with Translate Parameters

### ISSUE THREAD

**Issue by NicolasCampailla** [XmYx/deforum-comfy-nodes#12]
I'm having truble to get the deforum translation and rotation to work.
I've used one of the example nodes, and changed hte prompt and translation values. Here is the (slightly) modified workflow.

`{
  "last_node_id": 174,
  "last_link_id": 557,
  "nodes": [
    {
      "id": 154,
      "type": "DeforumDiffusionParamsNode",
      "pos": [
        -310,
        440
      ],
      "size": {
        "0": 278.891845703125,
        "1": 274
      },
      "flags": {},
      "order": 10,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 550
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            540
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumDiffusionParamsNode"
      },
      "widgets_values": [
        "0: (0.03)",
        "0: (0.50)",
        "0: (1.0)",
        "0: (5)",
        false,
        "0: (25)",
        false,
        "0:(0)",
        false,
        "0:(1)"
      ]
    },
    {
      "id": 157,
      "type": "DeforumHybridScheduleNode",
      "pos": [
        -310,
        760
      ],
      "size": {
        "0": 274.891845703125,
        "1": 178
      },
      "flags": {},
      "order": 11,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 540
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            541
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumHybridScheduleNode"
      },
      "widgets_values": [
        "0:(0.5)",
        "0:(0.5)",
        "0:(1)",
        "0:(100)",
        "0:(0)",
        "0:(0.8)"
      ]
    },
    {
      "id": 151,
      "type": "DeforumDepthParamsNode",
      "pos": [
        -670,
        530
      ],
      "size": {
        "0": 317.4000244140625,
        "1": 178
      },
      "flags": {},
      "order": 6,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 497
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            498
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumDepthParamsNode"
      },
      "widgets_values": [
        true,
        "Zoe",
        0.2,
        "border",
        "bicubic",
        false
      ]
    },
    {
      "id": 16,
      "type": "PreviewImage",
      "pos": [
        1344,
        83
      ],
      "size": {
        "0": 894.2135009765625,
        "1": 941.8845825195312
      },
      "flags": {},
      "order": 19,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 462,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "PreviewImage"
      }
    },
    {
      "id": 170,
      "type": "Note",
      "pos": [
        484,
        -347
      ],
      "size": {
        "0": 633.6494140625,
        "1": 221.03656005859375
      },
      "flags": {},
      "order": 0,
      "mode": 0,
      "properties": {
        "text": ""
      },
      "widgets_values": [
        "Welcome to Deforum!\n\nThe below graph provides a pluggable Deforum Animation pipeline in ComfyUI. It works frame-by-frame, so the best practice is to enable Extra options, and Auto Queue.\n\nDeforum Parameter and Schedule nodes represent all settings available to consume after chaining up by the Deforum Iterator node, which keeps track of the current frame, generates/gets the cached latent to be denoised in the next pass. The parameters and schedule's are the same as in the auto1111 extension and in the Colab version.\n\nHybrid nodes are currently bypassed (purple), enabling them, and selecting a video transforms the pipeline into Deforum Hybrid. Iteration can be reset to frame 0 with the reset value being set to 1 on the iterator node. Don't forget to switch it back to 0 to use the generated image/latent.\"\n\nDeforum Video Save node dumps its collected frames when the current frame's id reaches/has passed max_frames."
      ],
      "color": "#432",
      "bgcolor": "#653"
    },
    {
      "id": 153,
      "type": "DeforumNoiseParamsNode",
      "pos": [
        -310,
        990
      ],
      "size": {
        "0": 272.06170654296875,
        "1": 298
      },
      "flags": {},
      "order": 12,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 541
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            543
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumNoiseParamsNode"
      },
      "widgets_values": [
        true,
        "0: (0.8)",
        "0: (0.1)",
        "0: (5)",
        "0: (1.0)",
        "0: (0.0)",
        "perlin",
        8,
        8,
        4,
        0.5
      ]
    },
    {
      "id": 135,
      "type": "DeforumGetCachedLatentNode",
      "pos": [
        132,
        1291
      ],
      "size": {
        "0": 235.1999969482422,
        "1": 26
      },
      "flags": {},
      "order": 1,
      "mode": 0,
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            544
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumGetCachedLatentNode"
      }
    },
    {
      "id": 133,
      "type": "DeforumConditioningBlendNode",
      "pos": [
        640,
        -40
      ],
      "size": {
        "0": 342.5999755859375,
        "1": 78
      },
      "flags": {},
      "order": 14,
      "mode": 0,
      "inputs": [
        {
          "name": "clip",
          "type": "CLIP",
          "link": 428
        },
        {
          "name": "deforum_frame_data",
          "type": "DEFORUM_FRAME_DATA",
          "link": 546
        }
      ],
      "outputs": [
        {
          "name": "POSITIVE",
          "type": "CONDITIONING",
          "links": [
            430
          ],
          "shape": 3
        },
        {
          "name": "NEGATIVE",
          "type": "CONDITIONING",
          "links": [
            431
          ],
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumConditioningBlendNode"
      },
      "widgets_values": [
        "linear"
      ]
    },
    {
      "id": 150,
      "type": "DeforumAnimParamsNode",
      "pos": [
        -670,
        280
      ],
      "size": {
        "0": 317.4000244140625,
        "1": 178
      },
      "flags": {},
      "order": 5,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 537
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            497
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumAnimParamsNode"
      },
      "widgets_values": [
        "3D",
        120,
        "wrap",
        false,
        "20230129210106",
        false
      ]
    },
    {
      "id": 127,
      "type": "CheckpointLoaderSimple",
      "pos": [
        91,
        743
      ],
      "size": {
        "0": 315,
        "1": 98
      },
      "flags": {},
      "order": 2,
      "mode": 0,
      "outputs": [
        {
          "name": "MODEL",
          "type": "MODEL",
          "links": [
            533
          ],
          "shape": 3,
          "slot_index": 0
        },
        {
          "name": "CLIP",
          "type": "CLIP",
          "links": [
            428
          ],
          "shape": 3,
          "slot_index": 1
        },
        {
          "name": "VAE",
          "type": "VAE",
          "links": [],
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "CheckpointLoaderSimple"
      },
      "widgets_values": [
        "enchanterix25D_aetherV10.safetensors"
      ]
    },
    {
      "id": 173,
      "type": "VAELoader",
      "pos": [
        90,
        610
      ],
      "size": {
        "0": 315,
        "1": 58
      },
      "flags": {},
      "order": 3,
      "mode": 0,
      "outputs": [
        {
          "name": "VAE",
          "type": "VAE",
          "links": [
            552
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "VAELoader"
      },
      "widgets_values": [
        "color101VAE_v1.safetensors"
      ]
    },
    {
      "id": 141,
      "type": "Reroute",
      "pos": [
        530,
        720
      ],
      "size": [
        75,
        26
      ],
      "flags": {},
      "order": 15,
      "mode": 0,
      "inputs": [
        {
          "name": "",
          "type": "*",
          "link": 547
        }
      ],
      "outputs": [
        {
          "name": "",
          "type": "DEFORUM_FRAME_DATA",
          "links": [
            459
          ],
          "slot_index": 0
        }
      ],
      "properties": {
        "showOutputText": false,
        "horizontal": false
      }
    },
    {
      "id": 130,
      "type": "DeforumKSampler",
      "pos": [
        650,
        120
      ],
      "size": {
        "0": 325.93902587890625,
        "1": 106
      },
      "flags": {},
      "order": 16,
      "mode": 0,
      "inputs": [
        {
          "name": "model",
          "type": "MODEL",
          "link": 533
        },
        {
          "name": "latent",
          "type": "LATENT",
          "link": 548,
          "slot_index": 1
        },
        {
          "name": "positive",
          "type": "CONDITIONING",
          "link": 430
        },
        {
          "name": "negative",
          "type": "CONDITIONING",
          "link": 431,
          "slot_index": 3
        },
        {
          "name": "deforum_frame_data",
          "type": "DEFORUM_FRAME_DATA",
          "link": 459
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": [
            416,
            556
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumKSampler"
      }
    },
    {
      "id": 136,
      "type": "DeforumCacheLatentNode",
      "pos": [
        990,
        120
      ],
      "size": {
        "0": 210,
        "1": 26
      },
      "flags": {},
      "order": 18,
      "mode": 0,
      "inputs": [
        {
          "name": "latent",
          "type": "LATENT",
          "link": 556
        }
      ],
      "outputs": [
        {
          "name": "LATENT",
          "type": "LATENT",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumCacheLatentNode"
      }
    },
    {
      "id": 131,
      "type": "VAEDecode",
      "pos": [
        690,
        310
      ],
      "size": {
        "0": 210,
        "1": 46
      },
      "flags": {},
      "order": 17,
      "mode": 0,
      "inputs": [
        {
          "name": "samples",
          "type": "LATENT",
          "link": 416
        },
        {
          "name": "vae",
          "type": "VAE",
          "link": 552,
          "slot_index": 1
        }
      ],
      "outputs": [
        {
          "name": "IMAGE",
          "type": "IMAGE",
          "links": [
            462,
            557
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "VAEDecode"
      }
    },
    {
      "id": 172,
      "type": "DeforumBaseParamsNode",
      "pos": [
        -310,
        -60
      ],
      "size": {
        "0": 317.4000244140625,
        "1": 442
      },
      "flags": {},
      "order": 9,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 549
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            550
          ],
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumBaseParamsNode"
      },
      "widgets_values": [
        360,
        640,
        "euler",
        "normal",
        25,
        7,
        1,
        "Deforum_{timestring}",
        "fixed",
        1,
        "output/deforum",
        0.8,
        true,
        false,
        false,
        true,
        false
      ]
    },
    {
      "id": 126,
      "type": "DeforumPromptNode",
      "pos": [
        -670,
        -50
      ],
      "size": {
        "0": 313.04736328125,
        "1": 276.55352783203125
      },
      "flags": {},
      "order": 4,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": null
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            537
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumPromptNode"
      },
      "widgets_values": [
        "0:'fractal, mandelbulb, 3d, space, nature'"
      ]
    },
    {
      "id": 174,
      "type": "Image Save",
      "pos": [
        950,
        310
      ],
      "size": {
        "0": 320,
        "1": 560
      },
      "flags": {},
      "order": 20,
      "mode": 0,
      "inputs": [
        {
          "name": "images",
          "type": "IMAGE",
          "link": 557
        }
      ],
      "properties": {
        "Node name for S&R": "Image Save"
      },
      "widgets_values": [
        "C:\\Users\\nicol\\Desktop\\New folder (2)",
        "ComfyUI",
        "_",
        4,
        "false",
        "png",
        100,
        "false",
        "false",
        "false",
        "true",
        "true",
        "true"
      ]
    },
    {
      "id": 155,
      "type": "DeforumColorParamsNode",
      "pos": [
        -670,
        1120
      ],
      "size": {
        "0": 317.4000244140625,
        "1": 154
      },
      "flags": {},
      "order": 8,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 535
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            549
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumColorParamsNode"
      },
      "widgets_values": [
        "LAB",
        "",
        1,
        false,
        false
      ]
    },
    {
      "id": 152,
      "type": "DeforumTranslationParamsNode",
      "pos": [
        -670,
        780
      ],
      "size": {
        "0": 317.4000244140625,
        "1": 274
      },
      "flags": {},
      "order": 7,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 498
        }
      ],
      "outputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "links": [
            535
          ],
          "shape": 3,
          "slot_index": 0
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumTranslationParamsNode"
      },
      "widgets_values": [
        "0:(5)",
        "0:(-5)",
        "0:(-5)",
        "0:(-5)",
        "0:(-5)",
        "0:(5)",
        "0:(5)",
        "0:(5)",
        "0:(5)",
        "0:(5)"
      ]
    },
    {
      "id": 171,
      "type": "DeforumIteratorNode",
      "pos": [
        55,
        918
      ],
      "size": {
        "0": 393,
        "1": 286
      },
      "flags": {},
      "order": 13,
      "mode": 0,
      "inputs": [
        {
          "name": "deforum_data",
          "type": "deforum_data",
          "link": 543
        },
        {
          "name": "latent",
          "type": "LATENT",
          "link": 544
        },
        {
          "name": "init_latent",
          "type": "LATENT",
          "link": null
        }
      ],
      "outputs": [
        {
          "name": "deforum_frame_data",
          "type": "DEFORUM_FRAME_DATA",
          "links": [
            546,
            547
          ],
          "shape": 3
        },
        {
          "name": "latent",
          "type": "LATENT",
          "links": [
            548
          ],
          "shape": 3
        },
        {
          "name": "positive_prompt",
          "type": "STRING",
          "links": null,
          "shape": 3
        },
        {
          "name": "negative_prompt",
          "type": "STRING",
          "links": null,
          "shape": 3
        }
      ],
      "properties": {
        "Node name for S&R": "DeforumIteratorNode"
      },
      "widgets_values": [
        "stable_diffusion",
        218856197889948,
        "randomize",
        0,
        0.8,
        0.1,
        false,
        false
      ]
    }
  ],
  "links": [
    [
      416,
      130,
      0,
      131,
      0,
      "LATENT"
    ],
    [
      428,
      127,
      1,
      133,
      0,
      "CLIP"
    ],
    [
      430,
      133,
      0,
      130,
      2,
      "CONDITIONING"
    ],
    [
      431,
      133,
      1,
      130,
      3,
      "CONDITIONING"
    ],
    [
      459,
      141,
      0,
      130,
      4,
      "DEFORUM_FRAME_DATA"
    ],
    [
      462,
      131,
      0,
      16,
      0,
      "IMAGE"
    ],
    [
      497,
      150,
      0,
      151,
      0,
      "deforum_data"
    ],
    [
      498,
      151,
      0,
      152,
      0,
      "deforum_data"
    ],
    [
      533,
      127,
      0,
      130,
      0,
      "MODEL"
    ],
    [
      535,
      152,
      0,
      155,
      0,
      "deforum_data"
    ],
    [
      537,
      126,
      0,
      150,
      0,
      "deforum_data"
    ],
    [
      540,
      154,
      0,
      157,
      0,
      "deforum_data"
    ],
    [
      541,
      157,
      0,
      153,
      0,
      "deforum_data"
    ],
    [
      543,
      153,
      0,
      171,
      0,
      "deforum_data"
    ],
    [
      544,
      135,
      0,
      171,
      1,
      "LATENT"
    ],
    [
      546,
      171,
      0,
      133,
      1,
      "DEFORUM_FRAME_DATA"
    ],
    [
      547,
      171,
      0,
      141,
      0,
      "*"
    ],
    [
      548,
      171,
      1,
      130,
      1,
      "LATENT"
    ],
    [
      549,
      155,
      0,
      172,
      0,
      "deforum_data"
    ],
    [
      550,
      172,
      0,
      154,
      0,
      "deforum_data"
    ],
    [
      552,
      173,
      0,
      131,
      1,
      "VAE"
    ],
    [
      556,
      130,
      0,
      136,
      0,
      "LATENT"
    ],
    [
      557,
      131,
      0,
      174,
      0,
      "IMAGE"
    ]
  ],
  "groups": [],
  "config": {},
  "extra": {
    "groupNodes": {}
  },
  "version": 0.4
}`

Thank you in advance for the help!

**Comment by XmYx** [comment]
The workflow you provided has no FrameWarp in it, but directly caches the latent output of the KSampler. From the examples, open deforum_base.json, and see the usage of Image Operations after generation, in short, after decoding, you can do your image ops (Frame Warp, Hybrid, Add Noise, etc), re-encode, and then feed into the cache latent node.

**Comment by NicolasCampailla** [comment]
Sorry for wasting your time! Thank you for the help

**Comment by XmYx** [comment]
Absolutely no time wasted. If you seek any help regarding usage, you are always welcome to join our discord:
https://discord.gg/deforum

If you find any bugs or issues, this is still a great place to track.
Thank you!
