### ISSUE TITLE
How to set a prompt?

### ISSUE THREAD

**Issue by PLEXATIC** [XmYx/deforum-comfy-nodes#15]
I tried using this, but I cannot find any node to give a prompt..?
As far as I understand everything (loaded model + deforum data) should be given to the pipeline in the end. However the only node that allows me to add a prompt is areaPrompt and it didnt work for me (no matter what area size)...
I just get images of something like a colorful space artwork.

**Comment by XmYx** [comment]
Please open the base example from the examples folder.
![Screenshot 2024-03-01 185212](https://github.com/XmYx/deforum-comfy-nodes/assets/28485146/dae2ea47-a37b-44d8-b379-44cdb26e93bd)
Prompt node:
![Screenshot 2024-03-02 083639](https://github.com/XmYx/deforum-comfy-nodes/assets/28485146/169f376b-1f37-49b7-83b0-9b61244fd93e)

**Comment by XmYx** [comment]
Also, for usage related issues, ples join our discord to get direct help from us and our community.

https://discord.gg/deforum

**Comment by PLEXATIC** [comment]
oh I totally missed that, thanks a lot!
