### ISSUE TITLE
Nodes are failing in my comfy.

### ISSUE THREAD

**Issue by Pajaritaflora** [XmYx/deforum-comfy-nodes#17]
I was using them today and they stopped working with an error about the deforam conditioning  blend, I couldn't figure out what I changed to make that happen so I updated and now cannot get the nodes to import. They fail to come out of comfyui manager. Even though they were downloaded previously. 
Thanks for working on these nodes. I"m super excited to use them.

**Comment by XmYx** [comment]
Please make sure to update your ComfyUI, your Manager, and then press "Try update" in your Manager on the Deforum nodes.
If still errors, please post the Command Line output as well.

Thank you

**Comment by Pajaritaflora** [comment]
![Screenshot (48)](https://github.com/XmYx/deforum-comfy-nodes/assets/60947728/1035db6f-bdb6-4373-bca1-f554f29f3050)

**Comment by Pajaritaflora** [comment]
I updated comfy and updated all and updated the nodes and updated without the manager and refreshed. I still have no nodes working.

**Comment by Pajaritaflora** [comment]
Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_cspnodes
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AnimateLCM
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-optical-flow
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-deepcache
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\juggernaut-xl
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\zeroscope_v2_576w
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ad_motion_loras
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SVD
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AIT
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InterpolateEverything
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_vid2vid
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\steerable-motion
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-video-batches
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-project
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\deforum-comfy-nodes
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Diffusers
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DDColor
   0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
   0.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_PoP
   0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
   0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-manager
   0.4 seconds (IMPORT FAILED): D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Jags_Audiotools
   0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.5 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.9 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CCSR
   1.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   4.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MotionDiff

**Comment by XmYx** [comment]
You have many packages failing. What python version are you using? It is recommended to use python 3.10 or 3.11 max for AI apps as of 2024 03., if you can, please delete your venv, and use virtualenv to create one instead.

`pip3 install virtualenv
python3 -m virtualenv venv -p=3.10`

From then, it's the same.

**Comment by Pajaritaflora** [comment]
ok ill work on it

**Comment by Pajaritaflora** [comment]
hmm, i'm using 3.11 maybe i need a reinstall. ugh.

**Comment by XmYx** [comment]
Reverted a commit that caused issues with depth models, please update the nodes, and use any depth model other then Zoe as that is currently not returning the correct depth maps, looking into a better implementation.

**Comment by XmYx** [comment]
make sure to remove deforum from the venv / outside of venv

(pip uninstall -y deforum)

Then update via the manager.

**Comment by Pajaritaflora** [comment]
i created a fresh install yesterday, would I still need to do this task?


MaryAnn Ead
Artist
*www.Pajaritaflora.com <http://www.pajaritaflora.com/>*
5202200387 phone

https://superrare.com/pajaritaflora


[image: Facebook] [image: Facebook]

**Comment by XmYx** [comment]
Only if you encounter any issues in the future. Closing this issue for now : )
