### ISSUE TITLE
Import failed,please help

### ISSUE THREAD

**Issue by Microfan09** [XmYx/deforum-comfy-nodes#18]
The node after installed,in manager show "import failed",help,please.
![install failed](https://github.com/XmYx/deforum-comfy-nodes/assets/161914169/fa1853e1-f05d-4174-91ab-3fff4930a4e1)

**Comment by Microfan09** [comment]
Thank you! It has worked,
but the example work flow is still not work, when I import or load it,that nothing happened.

**Comment by XmYx** [comment]
from the right menu Load https://github.com/XmYx/deforum-comfy-nodes/blob/main/examples/deforum_base.json, press Refresh on the same Comfy menu, and make sure you have an XL checkpoint selected on the CheckpointLoaderSimple node, then set enable_autoqueue to true on the Iterator node, and press Queue Prompt.

**Comment by Microfan09** [comment]
Thank you!

**Comment by w84itngetit** [comment]
> Hi, also please make sure to use python version 3.10



> Hi, also please make sure to use python version 3.10

HI, how can i downgrade python? i have python 3.11 in python_embeded folder

**Comment by blueangel1313** [comment]
I recommend using a venv and having that set to 3.10

https://docs.python.org/3/library/venv.html

**Comment by w84itngetit** [comment]
> I recommend using a venv and having that set to 3.10
> 
> https://docs.python.org/3/library/venv.html

Thank you, it's seems hard, but i ll research it)

**Comment by XmYx** [comment]
Reverted a commit that caused issues with depth models, please update the nodes, and use any depth model other then Zoe as that is currently not returning the correct depth maps, looking into a better implementation.

**Comment by XmYx** [comment]
make sure to remove deforum from the venv / outside of venv

(pip uninstall -y deforum)

Then update via the manager.
