### ISSUE TITLE
the save video node reports an error 

### ISSUE THREAD

**Issue by doulove3** [XmYx/deforum-comfy-nodes#21]
When executing to the last frame, the save video node reports an error message of "TypeError: must be real number, not NoneType", unable to store the video file.
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/163579024/fc14a9b3-3d50-4dea-aeb8-37f9a1c9aa25)

**Comment by doulove3** [comment]
Comfyui has been upgraded to the latest version, Python 3.10.11
Thank you very much for making the plugin，Thank you for your help

**Comment by XmYx** [comment]
can you try refreshing the page, and right click - fix node on the videosave node?

**Comment by doulove3** [comment]
I have tried the fix node, but after clicking on it, the cached frame is lost and there is still no video file stored.

**Comment by XmYx** [comment]
make sure to remove deforum from the venv / outside of venv

(pip uninstall -y deforum)

Then update via the manager.

**Comment by doulove3** [comment]
After reinstalling and upgrading Deforum, the problem still did not solve. Later, I reinstalled Comfyui and then installed Deforum. The problem was resolved, which may be related to the dependent environment, but I am not sure where the problem is. Thank you very much for your reply and the support provided by Deferum.
