### ISSUE TITLE
name issue  'get_flow_for_hybrid_motion_preyV_imgs

### ISSUE THREAD

**Issue by cardenluo** [XmYx/deforum-comfy-nodes#22]
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/133877069/989fa2bb-cd3b-4744-b55b-3bfd3cb5774e)
After I made the necessary replacements, the issue was resolved.

**Comment by XmYx** [comment]
you have an incorrect version of deforum installed, possibly outside of the venv/embedded environment. 
revert your changes, remove the pip installed deforum package from everywhere, and make sure to update the node package to the latest via the manager.

See the correct commit here:

https://github.com/XmYx/deforum-studio/blob/main/src/deforum/generators/deforum_flow_generator.py

**Comment by XmYx** [comment]
make sure to remove deforum from the venv / outside of venv

(pip uninstall -y deforum)

Then update via the manager.

**Comment by cardenluo** [comment]
after updated ,it work well now ,thanks
