### ISSUE TITLE
what's the problom

### ISSUE THREAD

**Issue by Elminsst** [XmYx/deforum-comfy-nodes#24]
how to fix this？
![微信图片_20240321140627](https://github.com/XmYx/deforum-comfy-nodes/assets/130235860/a72db7fb-d8a9-4032-bd55-fd0dbd0ea062)
![微信图片_20240321140635](https://github.com/XmYx/deforum-comfy-nodes/assets/130235860/963559da-24d3-445c-9779-6597151a449d)

**Comment by XmYx** [comment]
Please update to the latest version, and make sure to refresh the page after loading from json, before running. Pushed updated jsons that shouldnt require this, but in any case.
