### ISSUE TITLE
KSampler Settings

### ISSUE THREAD

**Issue by Mindspherical** [XmYx/deforum-comfy-nodes#30]
Is there any way for us to adjust step count and the scheduler? I'd like to use a lightning model with this. Thanks!

**Comment by XmYx** [comment]
Absolutely! The sampler name, scheduler, and steps_schedule parameters are the ones to look for on Base params node and Diffusion schedule node, then there is a deforum frame data extractor node that let's you plugin your favorite sampler with the given frame data as well.
