### ISSUE TITLE
Deforum Save Video not saving video

### ISSUE THREAD

**Issue by fresno808** [XmYx/deforum-comfy-nodes#33]
After generating, no video is created. I am using the workflows from the examples folder. Any idea on how to fix it?

**Comment by XmYx** [comment]
Hi! Please make sure to refresh the page after loading the workflow, additionally, right click - Fix Node as sometimes comfy-s deserialization breaks saved graphs, we're looking into some fix, but you can confirm by seeing some dropdowns with completely invalid selections.
