### ISSUE TITLE
seed scheduling option

### ISSUE THREAD

**Issue by SneakyKasstro** [XmYx/deforum-comfy-nodes#37]
i have been searching for this feature within the nodes, but cant seem to pinpoint it, also cant find the FOV scheduling..

are these still schedulable?

**Comment by kuzman123** [comment]
Same here...

**Comment by XmYx** [comment]
Added seed_schedule field to the base params node, please Right Click - Fix Node on it after updating for it to show up, and you may use a Frame Data Extract node to get the scheduled seed for the relevant frame.
