### ISSUE TITLE
Deforum Prompt Node Error

### ISSUE THREAD

**Issue by alienufosoul** [XmYx/deforum-comfy-nodes#39]
![Screenshot 2024-06-13 180730](https://github.com/XmYx/deforum-comfy-nodes/assets/17532290/4344dc12-79a1-4bc5-ab4d-0d9db0882a18)

getting this error after the new update. need help

**Comment by XmYx** [comment]
that node wasnt changed, maybe you have an extra empty line?

**Comment by alienufosoul** [comment]
![Screenshot 2024-06-13 183220](https://github.com/XmYx/deforum-comfy-nodes/assets/17532290/fc02fcf2-ae33-49e6-b53c-54508c31fd14)

getting the same error with one prompt also

**Comment by alienufosoul** [comment]
got it resolved, just like you said I left an extra line. Thanks for the help buddy
