### ISSUE TITLE
auto queue copncept is not explained in default graph

### ISSUE THREAD

**Issue by deforum** [XmYx/deforum-comfy-nodes#4]
i think it would be a good idea to add text to the default graph to explain the auto queue concept
![Screenshot from 2024-02-11 11-34-08](https://github.com/XmYx/deforum-comfy-nodes/assets/110359942/3b98e9bc-7625-474a-b636-cbb0763548cd)

**Comment by XmYx** [comment]
pls check notes if they are easy to understand, and let's add further explanation if needed
