### ISSUE TITLE
Error occurred when executing DeforumIteratorNode:  'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by guchendesigndog** [XmYx/deforum-comfy-nodes#46]
![c86427a26d563202d35ecd9af9b13a4](https://github.com/user-attachments/assets/60a36e91-13a2-4a33-90a9-cd644163a91c)
Error occurred when executing DeforumIteratorNode:

'NoneType' object is not subscriptable
很奇怪的是我使用所有者的例子工作流可以使用，不好的地方就是效果不好，仿佛没有降噪，但是当我更改任意参数时就开始汇报此类错误，寻找了一天无法解决，

**Comment by guchendesigndog** [comment]
请问作者或者某位大佬是否知道此问题如何解决

**Comment by XmYx** [comment]
Please refresh the page after loading the json.

**Comment by guchendesigndog** [comment]
无论如何总有某个节点会报错，当这个节点没有问题下个节点就会开始报错，工作流很难顺利使用，可能是我操作有误，能否请求作者发布使用文档等类似内容，相信会对很多人帮助很大

**Comment by guchendesigndog** [comment]
谢谢作者，我已经解决，是我本人操作问题，节点工作流现在已经可以正常运行，请问作者，我该如何像webui一样设置起始帧和间隔帧参考呢，
