### ISSUE TITLE
comfyui log show  IMPORT FAILED

### ISSUE THREAD

**Issue by mic1user1** [XmYx/deforum-comfy-nodes#56]
deforum-comfy-nodes has been installed, but after comfyui is started, the log shows (IMPORT FAILED): G:\comfyui\custom_nodes\deforum-comfy-nodes. How can I solve this problem?

**Comment by LUDEEEE** [comment]
Same

**Comment by weisiren000** [comment]
> 相同的

1

**Comment by lunatico67** [comment]
> deforum-comfy-nodes has been installed, but after comfyui is started, the log shows (IMPORT FAILED): G:\comfyui\custom_nodes\deforum-comfy-nodes. How can I solve this problem?

Same here on windows 11. Have you found a solution?

**Comment by XmYx** [comment]
Please make sure to uninstall 'deforum', the underlying backend library ( https://github.com/XmYx/deforum-studio ), and that you reinstall the node package as well. A fix was pushed and tested on a fresh Comfy installation.

**Comment by lunatico67** [comment]
> Please make sure to uninstall 'deforum', the underlying backend library ( https://github.com/XmYx/deforum-studio ), and that you reinstall the node package as well. A fix was pushed and tested on a fresh Comfy installation.

Hi XmYx
Thanks for the help but for me does not work.
Please make sure to uninstall 'deforum', the underlying backend library  ( Where is placed the underlying backend library?)
I I remove the deforum-comfy node through the comfyuI manager and it doesn't work when I reinstall it.

**Comment by XmYx** [comment]
In your virtual environment, installed as a pip package, to uninstall, run 'pip uninstall deforum'

**Comment by lunatico67** [comment]
Here cmd to open in Terminal and write pip uninstall deforum

![pythonembeded](https://github.com/user-attachments/assets/abac64a3-77c2-4cb3-ad43-2ac9431d29ea)

**Comment by lunatico67** [comment]
![pythonembeded](https://github.com/user-attachments/assets/2577fa9c-0fbb-4819-a95e-5f730103678c)

Here cmd to open in Terminal and write pip uninstall deforum

**Comment by lunatico67** [comment]
![Virtualenv](https://github.com/user-attachments/assets/4f0abb51-2cd5-43f9-9097-4e541f175a68)

Here cmd to open in Terminal and write pip uninstall deforum ?

**Comment by XmYx** [comment]
If on windows, there open cmd, activate.bat, then pip uninstall deforum.

**Comment by lunatico67** [comment]
Hi

![activate](https://github.com/user-attachments/assets/7f86e846-30da-4cbd-816b-2a2100238d6c)

**Comment by lunatico67** [comment]
Hi

![activatebat](https://github.com/user-attachments/assets/2b79ea8c-70fd-451e-8e93-3d14a3335cb4)

**Comment by lunatico67** [comment]
![activatebat](https://github.com/user-attachments/assets/9dc1dd65-42a3-429d-ba7c-0f5e08489466)

**Comment by XmYx** [comment]
> ![activatebat](https://private-user-images.githubusercontent.com/79542282/393171964-9dc1dd65-42a3-429d-ba7c-0f5e08489466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM0OTQ3MzksIm5iZiI6MTczMzQ5NDQzOSwicGF0aCI6Ii83OTU0MjI4Mi8zOTMxNzE5NjQtOWRjMWRkNjUtNDJhMy00MjlkLWJhN2MtMGY1ZTA4NDg5NDY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA2VDE0MTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYjVmNDc1YjkzMWVhNTMxZGIxYWNmOWFjYzliYTQ4YmJmMDFhZjQyMmIwZWNiZGNkNDM5MzgwYmI4OGUzZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.6X9_ADm42E70Jl-lk7JwgDvEZkUGDzzQQJxYHHqbx6g)

This is not your venv folder. In fact, you don't have one as you are using the portable version of comfy which has an embedded python (with a typo). The folder you are in now is the python package, virtualenv, which gets called when you use <python_executable> -m virtualenv to create a venv for an example.

I personally do not use embedded python, nor can give valuable advice how to manage it, as it's too cumbersome to even think about it. Just reinstall ComfyUI, and install deforum from the manager, that's way way way quicker.

**Comment by lunatico67** [comment]
Excuse my ignorance, I didn't know there were two types of installation in comfyui. Thanks for your advice. The problem is that I already have a lot of custom nodes installed and it's horrible to start again from scratch. The day it stops working (it has happened to me some times, I will do it). Have a nice weekend, thanks

**Comment by XmYx** [comment]
5 - 6.. even more.. Docker, venv, virtualenv, conda, embedded, - not sure how the standalone version handles the environment.

Although you should be able to press Try Fix in the Manager, I acually included the reinstall step for the backend deforum package if it runs correctly.

Try once, and let me know if it worked.

**Comment by ritonV** [comment]
Same problem for me. I don't have portable version. After Try Fix, it does not change.

**Comment by lunatico67** [comment]
Hi XmYx
Sorry for the delay in my reply, I see it now. I have started with a new installation of comfyui portable version and the same problem, it doesn't work. I don't know if deforum is incompatible with the portable version. Thanks for your help, I'm giving it up as impossible.

**Comment by aieio** [comment]
Still no fix on this? running into the same issue

**Comment by XmYx** [comment]
fixed in [602d7d9](https://github.com/XmYx/deforum-comfy-nodes/commit/602d7d94c6d8727555acd363395416a9cdba3c21)

Update the nodes, and run "Try Fix" on them, in case of any issues, make sure to remove the installed deforum package with pip from the venv or the portable installation's python.

I've ran a fresh installation on linux with the following:

`conda create --name comfy-deforum python=3.11
conda activate comfy-deforum
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
git clone https://github.com/comfyanonymous/ComfyUI
cd ComfyUI
pip install -r requirements.txt
cd custom_nodes
git clone https://github.com/ltdrdata/ComfyUI-Manager
cd ComfyUI-Manager
pip install -r requirements.txt
cd ..
git clone https://github.com/XmYx/deforum-comfy-nodes
cd ..
python main.py`

`2025-02-11 20:14:45.558 - __init__.py:1706 - INFO -    0.0 seconds: /home/mix/ComfyUI/custom_nodes/websocket_image_save.py
2025-02-11 20:14:45.558 - __init__.py:1706 - INFO -    0.0 seconds: /home/mix/ComfyUI/custom_nodes/ComfyUI-Manager
2025-02-11 20:14:45.558 - __init__.py:1706 - INFO -    0.6 seconds: /home/mix/ComfyUI/custom_nodes/deforum-comfy-nodes
2025-02-11 20:14:45.558 - __init__.py:1706 - INFO - 
2025-02-11 20:14:45.562 - __init__.py:1706 - INFO - Starting server

2025-02-11 20:14:45.562 - __init__.py:1706 - INFO - To see the GUI go to: http://127.0.0.1:8188`

**Comment by aieio** [comment]
Try Fix does not work for me, and there is no option to update the Deforum nodes.
I am running ComfyUI (on Windows 10) using the application that I got from Comfy.org, it is running Python v 3.12.8 and I am unclear on where I should run "pip uninstall deforum", or if it is even compatible with this comfyui setup/python version. I tried running the uninstall command in the ".venv" folder and had no luck. I also have a portable version of Comfyui installed in a separate folder, and have tried running "pip uninstall deforum" in the "venv" folder. It provided the message "skipping deforum as it is not installed". Apologies for my ignorance.

**Comment by XmYx** [comment]
> Try Fix does not work for me. I am running ComfyUI (on Windows 10) using the application that I got from Comfy.org, it is running Python v 3.12.8 and I am unclear on where I should run "pip uninstall deforum", or if it is even compatible with this comfyui setup/python version. I tried running the uninstall command in the ".venv" folder and had no luck. I also have a portable version of Comfyui installed in a separate folder, and have tried running "pip uninstall deforum" in the "venv" folder. It provided the message "skipping deforum as it is not installed". Apologies for my ignorance.

Reinstall Comfy with the steps listed:

conda create --name comfy-deforum python=3.11
conda activate comfy-deforum
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124
git clone https://github.com/comfyanonymous/ComfyUI
cd ComfyUI
pip install -r requirements.txt
cd custom_nodes
git clone https://github.com/ltdrdata/ComfyUI-Manager
cd ComfyUI-Manager
pip install -r requirements.txt
cd ..
git clone https://github.com/XmYx/deforum-comfy-nodes
cd ..
python main.py

I personally discourage using the pre-packed version, I also at this point discourage the usage of python 3.12. Excuse my ignorance, it takes way way shorter time to properly install Comfy then to debug an old beast : )

**Comment by aieio** [comment]
> > Try Fix does not work for me. I am running ComfyUI (on Windows 10) using the application that I got from Comfy.org, it is running Python v 3.12.8 and I am unclear on where I should run "pip uninstall deforum", or if it is even compatible with this comfyui setup/python version. I tried running the uninstall command in the ".venv" folder and had no luck. I also have a portable version of Comfyui installed in a separate folder, and have tried running "pip uninstall deforum" in the "venv" folder. It provided the message "skipping deforum as it is not installed". Apologies for my ignorance.
> 
> Remove the deforum node package, start comfy, reinstall it using the manager, or reinstall Comfy with the steps listed:
> 
> conda create --name comfy-deforum python=3.11 conda activate comfy-deforum pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124 git clone https://github.com/comfyanonymous/ComfyUI cd ComfyUI pip install -r requirements.txt cd custom_nodes git clone https://github.com/ltdrdata/ComfyUI-Manager cd ComfyUI-Manager pip install -r requirements.txt cd .. git clone https://github.com/XmYx/deforum-comfy-nodes cd .. python main.py
> 
> I personally discourage using the pre-packed version, I also at this point discourage the usage of python 3.12. Excuse my ignorance, it takes way way shorter time to properly install Comfy then to debug an old beast : )

Thanks, I got it running now.

I was struggling a bit at first but some googling helped me figure out that I needed to have miniconda installed, along with the path added to the environment variables.
