### ISSUE TITLE
Usage of multiple Lora in the same prompt (DeforumConditioningBlendNode)

### ISSUE THREAD

**Issue by AIconfig** [XmYx/deforum-comfy-nodes#6]
It seems that some combinations of some Loras used in the same prompt throws an error `DeforumConditioningBlendNode`. 
The same prompt with the same Checkpoint and Lora's work in Automatic1111 Deforum extension. 
If I use those Loras separately in a prompt - everything works. 
The workflow used is the [deforum_base.json](https://github.com/XmYx/deforum-comfy-nodes/blob/main/examples/deforum_base.json) which comes in `example` folder. The only change is the prompt and the Checkpoint used. All other settings are left unmodified.
 Deforum prompt: 
```
0:'<lora:frog-ponyxl-v1:1> , fr0g, <lora:bigeyes-ponyxl-v1:1> , b1g3y3s, a frog man, <lora:add-detail-xl:0.7>, <lora:xl_more_art-full_v1:0.1>'
100:'dart vader in the desert, DUNE GIANT WORM, by moebius'
```
Checkpoint used: [realcartoonXL_v4](https://civitai.com/models/125907?modelVersionId=171099)
Loras used:
- `<lora:bigeyes-ponyxl-v1:1>` - [link](https://civitai.com/models/236233?modelVersionId=266345)
- `<lora:add-detail-xl:0.7>` -  [link](https://civitai.com/models/287712?modelVersionId=323592)
- `<lora:xl_more_art-full_v1:0.1>` -  [link](https://civitai.com/models/124347?modelVersionId=152309)
- `<lora:frog-ponyxl-v1:1>` -  [link](https://civitai.com/models/300810?modelVersionId=337854)

An error produced:
```
Error occurred when executing DeforumConditioningBlendNode:

The size of tensor a (77) must match the size of tensor b (154) at non-singleton dimension 1

  File "/home/AI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/AI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/AI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/AI/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/deforum_node.py", line 1255, in fn
    cond = blend_tensors(cond[0], next_cond[0], prompt_blend, blend_method)
  File "/home/AI/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/deforum_node.py", line 1213, in blend_tensors
    blended_cond = gaussian_blend(obj1[0], obj2[0], blend_value)
  File "/home/AI/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/deforum_node.py", line 1188, in gaussian_blend
    return (1 - weight) * tensor1 + weight * tensor2
```

Screenshot of the window with this error:
![Screenshot from 2024-02-14 01-14-58](https://github.com/XmYx/deforum-comfy-nodes/assets/142949181/57e66e56-5a35-44af-8c69-8fbd3587ab25)

An error in the console:
```
got prompt
[ Deforum Iterator: 12 / 100 0]
[ Deforum Conds: '<lora:frog-ponyxl-v1:1> , fr0g, <lora:bigeyes-ponyxl-v1:1> , b1g3y3s, a frog man, <lora:add-detail-xl:0.7>, <lora:xl_more_art-full_v1:0.1>',  ]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/AI/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/AI/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/AI/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/AI/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/deforum_node.py", line 1255, in fn
    cond = blend_tensors(cond[0], next_cond[0], prompt_blend, blend_method)
  File "/home/AI/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/deforum_node.py", line 1213, in blend_tensors
    blended_cond = gaussian_blend(obj1[0], obj2[0], blend_value)
  File "/home/AI/ComfyUI/custom_nodes/deforum-comfy-nodes/deforum_nodes/deforum_node.py", line 1188, in gaussian_blend
    return (1 - weight) * tensor1 + weight * tensor2
RuntimeError: The size of tensor a (77) must match the size of tensor b (154) at non-singleton dimension 1

Prompt executed in 0.24 seconds
```

The extension commit hash used in ComfyUI: 0efb7c1c6575c8bbc1f42381df6938a4f0a1f021

Unfortunately, I don't fully understand the error to be fair, but if someone has an idea of how to overcome this issues it would be great if you share your workaround.

**Comment by XmYx** [comment]
Hey!

The error you are experiencing is due to the prompt being too long, more precisely, that we are trying to blend conditionings with different tensor shapes, but also, Lora's cannot be called upon like that in ComfyUI.

For the deforum context, we will come up with a special DeforumLoraSchedule node, that iterates the Loaded Lora(s) based on what was set either in the prompt, or on the schedule node itself.

Remove those parts, and make sure your prompts are withing the original token limit of 77 when using Conditioning Blending, if you set that to None, prompt lengths may vary more.

In ComfyUI, currently, the way to load a Lora is to place a LoraLoader node between the CheckpointLoader and DeforumKSampler (or KSampler).

**Comment by AIconfig** [comment]
Thank you for explanation and tips about using the Lora correctly!
Do you know if the Deforum conditionings blending process is different in ComfyUI and Automatic1111? 
It's just I use way longer prompts (about 3 times longer prompts) in Automatic1111 Deforum extension and it doesn't have any problems processing such prompts there. However, in ComfyUI Deforum extension the prompts must be way shorter for some reason.

**Comment by XmYx** [comment]
Long Prompt Blending hasn't been implemented yet, but have an idea about it.
You can try setting the Conditioning Blending to 'None' or replacing the DeforumConditioningBlend node with two simple ClipTextEncode nodes, convert their prompt inputs to inputs, and connect with the relevant output of DeforumIteratorNode / relevant input of the sampler node.

We'll either do it internally, or with some conditional checks and as it's done by default in comfy, by using multiple conditionings, merging/blending them.

**Comment by AIconfig** [comment]
Thank you a lot! Changing Conditioning Blending to 'None' worked.
