### ISSUE TITLE
Error occurred when executing DeforumLoadVideo

### ISSUE THREAD

**Issue by cardenluo** [XmYx/deforum-comfy-nodes#8]
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/133877069/b62d4246-9573-4c68-a0b2-6c943cfc5aba)

**Comment by XmYx** [comment]
The Video Loader node expected a Video to be selected, when opening the file select, enter an * in the filename field (or *.mp4) to see all / only mp4 video files, then select one.
