### ISSUE TITLE
"'DeforumIteratorNode' object has no attribute 'rng'", OR "Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!"

### ISSUE THREAD

**Issue by hamster-poodle** [XmYx/deforum-comfy-nodes#9]
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/67736737/1f8c7e14-131a-43f6-b654-747f8277a1b3)

I've been using a this simple workflow, but I've encountered an issue that I can only generate a single image and the Iterator Node returns a "1". Following this, I'm unable to run the workflow again. I've attempted to use multiple Launchers for ComfyUI, specifically trying both the ComfyUI_windows_portable and Pinokio versions. However, in both cases, I'm still limited to generating just one image.

![image](https://github.com/XmYx/deforum-comfy-nodes/assets/67736737/8e9b2052-d152-464f-804f-a92feab11094)
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/67736737/a4b24983-bf39-4c42-abfb-171f5913950a)

**Comment by XmYx** [comment]
Hey! I've encountered the same error and just pushed a fix. Can you update via the manager?

**Comment by hamster-poodle** [comment]
Thank you for your response!
I wasn't able to run your workflows directly, but after enabling the "reset_latent" option on the Iterator Node, I managed to generate more than one image and saw the numbers on the Iterator Node go above 1.

I'm a bit unsure about the correct settings, as when I simply open the workflows, I encounter unusual settings like Seed=NaN, control_after_generate=0 (is this supposed to be fixed, incremented, randomized?), and seed_behavior=iter (this setting I'm not familiar with at all).
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/67736737/b2b58ae5-95c8-4e90-aadc-7b9e149f137d)

I just want you to share screen shots of your ComfyUI to make sure what is correct, not only Workflow if you can.
Thx!

**Comment by XmYx** [comment]
Yes, that's most definetely not correct, please try the updated example, if in doubt, right click on that Deform Sampler, and convert group back to nodes, and do a right click "fix node" on the iterator node to make sure it is set up correctly.

reset_latent and reset_counter should only be used if you want to reset the iteration, generate a first frame, then turn those off, and it is an img2img process with a latent always cached in the deforum cache latent node.

**Comment by XmYx** [comment]
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/28485146/3a2200c5-b937-4c93-8a1a-e11fc9c802b4)

**Comment by XmYx** [comment]
here it is unpacked:
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/28485146/9ad3ae25-5e1e-4f7f-9153-2b1edf24148f)

and sorted for better visibility what happens:
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/28485146/e54ba323-d25e-4660-9a09-3dcfe615dbe4)

**Comment by XmYx** [comment]
if the cached latent doesnt exist, or on frame 0, or reset_latent = true the iterator node disregards the cached latent, and generates a new one to start with, in any other case, it uses the input. loopbacks are not possible in comfy, therefore the implementation of this cache node. It's by the way kinda similar to how Unreal manages variables conincidentally.

**Comment by hamster-poodle** [comment]
Thanks for the screenshots! I've now understood the node settings.

As I mentioned earlier, I experimented with both the reset counter and latent settings ON and OFF.
Now, I've encountered a new error. It seems like the cache function isn't working properly.

![image](https://github.com/XmYx/deforum-comfy-nodes/assets/67736737/5be2054e-c821-417a-9abe-a2dfd6279da5)
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/67736737/23688a1f-1576-46c7-8b06-416b3082bd04)

**Comment by XmYx** [comment]
You really have to do an update on the node package, and use the updated example graph.

**Comment by XmYx** [comment]
If you used the Manager to install the node package, please open the Manager, go to Install custom nodes, search for Deforum and click Try Update, restart ComfyUI and select the updated deforum_simple.json to Load from the repo's example folder.

**Comment by hamster-poodle** [comment]
Yes, I did everything, manager stuff, git clone stuff, going to custom_node folder and delete it and reinstall...
This is still showing, I know you said fixed in other issue page.
![image](https://github.com/XmYx/deforum-comfy-nodes/assets/67736737/00833a39-360a-4892-80f2-cce27dfafd55)

I just have a trouble with Iterator node when I turn OFF "reset_latent".

**Comment by XmYx** [comment]
Would you be able to hop on our discord to the comfy-chat channel to get more direct help in your specific issue?

https://discord.gg/deforum

**Comment by hamster-poodle** [comment]
I moved and saw a person who faces same issue.
Could you see it on Comfy-Chat?

**Comment by hamster-poodle** [comment]
Fixed!
